# Generated by Django 5.2.7 on 2025-11-18 04:59

import apps.courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_content_file_image_text_vode'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='order',
            field=apps.courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=apps.courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
