# Generated by Django 5.2.7 on 2025-11-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_content_order_module_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
